# Generated by Django 2.2.7 on 2019-11-11 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profesional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=15)),
                ('horarioAtencion', models.CharField(max_length=15)),
                ('foto', models.ImageField(upload_to='images/')),
                ('areaAtencion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profesional.AreaAtencion')),
            ],
        ),
    ]
