# Generated by Django 2.2.7 on 2019-11-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesional', '0004_auto_20191112_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='sector',
            field=models.CharField(choices=[('R', 'ROJO'), ('A', 'AZUL')], default=('A', 'AZUL'), max_length=15),
        ),
    ]
