# Generated by Django 2.2.7 on 2019-11-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesional', '0006_auto_20191116_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='foto',
            field=models.ImageField(default='static/images/medicine.png', upload_to='images/profesionales/'),
        ),
    ]
