# Generated by Django 2.2.7 on 2019-11-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesional', '0007_auto_20191116_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='sector',
            field=models.CharField(choices=[('ROJO', 'R'), ('AZUL', 'AZ'), ('AMARILLO', 'AM'), ('VERDE', 'V')], default=('AZUL', 'AZ'), max_length=15),
        ),
    ]
