# Generated by Django 2.2.7 on 2019-11-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesional', '0008_auto_20191122_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='sector',
            field=models.CharField(choices=[('ROJO', 'ROJO'), ('AZUL', 'AZUL'), ('AMARILLO', 'AMARILLO'), ('VERDE', 'VERDE')], default=('AZUL', 'AZUL'), max_length=15),
        ),
    ]
