# Generated by Django 2.2.7 on 2019-11-10 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticias',
            old_name='fecha',
            new_name='fechaPublicacion',
        ),
    ]
