# Generated by Django 2.2.7 on 2019-11-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_auto_20191110_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='altura',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(default='direccion', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='estadoCivil',
            field=models.CharField(choices=[('S', 'Soltero'), ('V', 'Viudo'), ('C', 'Casado'), ('D', 'Divorsiado')], default=('V', 'Viudo'), max_length=10),
        ),
        migrations.AddField(
            model_name='paciente',
            name='numeroHijos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paciente',
            name='peso',
            field=models.IntegerField(default=99),
        ),
        migrations.AddField(
            model_name='paciente',
            name='problemasSalud',
            field=models.CharField(choices=[('C', 'Cardiaco'), ('E', 'Endocrino'), ('CI', 'Circulación'), ('D', 'Digestivo'), ('T', 'Tensión arterial'), ('N', 'Ninguno')], default=('N', 'Ninguno'), max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(default='99999999', max_length=9),
        ),
    ]
