# Generated by Django 2.2.7 on 2019-11-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_auto_20191121_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='rut',
            field=models.CharField(default=5, max_length=9),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='altura',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estadoCivil',
            field=models.CharField(choices=[('S', 'Soltero'), ('V', 'Viudo'), ('C', 'Casado'), ('D', 'Divorsiado')], default=('S', 'Soltero'), max_length=10),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numeroHijos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='peso',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
    ]
