# Generated by Django 2.2.7 on 2019-11-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_auto_20191122_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='estadoCivil',
            field=models.CharField(choices=[('Soltero', 'Soltero'), ('Viudo', 'Viudo'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado')], default=('Soltero', 'Soltero'), max_length=10),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='problemasSalud',
            field=models.CharField(choices=[('Cardiaco', 'Cardiaco'), ('Endocrino', 'Endocrino'), ('Circulación', 'Circulación'), ('Digestivo', 'Digestivo'), ('Tensión arterial', 'Tensión arterial'), ('Ninguno', 'Ninguno')], default=('Ninguno', 'Ninguno'), max_length=20),
        ),
    ]
